### ISSUE TITLE
unknown message id's from camera cause exception and stream abort

### ISSUE THREAD

**Issue by rpnoll1977** [jdillenkofer/camera_proxy#4]
Hi, great work. I have an argus pt installed. The camera proxy is working after adding 0x4F to the list of known BAICHUAN_MESSAGE_IDs

**Comment by jdillenkofer** [comment]
Hi,
i added the 0x4f message id to the list.
Do you know what this message type is used for?
Can you check if everything still works with the latest version on the develop branch?

**Comment by rpnoll1977** [comment]
problem is fixed, thank you. if i have some time i will have a look at the message contents

**Comment by jdillenkofer** [comment]
Thank you for the bug report. I think there may be more message ids that can abort the stream.
I will leave this issue open until one of us finds out what the message id bytes 0xea and 0x4f are actually used for.

**Comment by rpnoll1977** [comment]
The message is sent once at the start of the video transmission. Something about serial port parameters. 

pi@raspberrypi:~/camera_proxy $ python3 src/main.py --debug
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: ##
INFO:baichuan_udp_layer:Sending discovery packet
INFO:baichuan_udp_layer:Sending discovery packet
INFO:baichuan_udp_layer:Sending discovery packet
INFO:baichuan_udp_layer:Sending discovery packet
INFO:baichuan_udp_layer:Sending discovery packet
INFO:baichuan_udp_layer:Sending discovery packet
INFO:baichuan_udp_layer:Received discovery packet answer from ##
INFO:camera:Sending legacy login packet
INFO:camera:Receiving nonce packet
INFO:camera:Received nonce: ##
INFO:camera:Sending modern login packet
INFO:camera:Send start video cmd
DEBUG:camera:Sending ping
DEBUG:camera:Received unhandled message. modern_message_id: 4115027578
DEBUG:camera:I Frame found
DEBUG:camera:AAC Frame found (l_size 256, r_size 256)
WARNING:libav.swscaler:No accelerated colorspace conversion found from yuv420p to rgb24.
DEBUG:camera:P Frame found
INFO:werkzeug:127.0.0.1 - - [09/Nov/2020 21:07:36] "GET /api/v1/cameras/camera1/stream HTTP/1.1" 200 -
DEBUG:camera:AAC Frame found (l_size 256, r_size 256)
DEBUG:camera:P Frame found
DEBUG:camera:Received pong
DEBUG:camera:0x4F
DEBUG:camera:<?xml version="1.0" encoding="UTF-8" ?>
<body>
    <Serial version="1.1">
        <channelId>0</channelId>
        <baudRate>9600</baudRate>
        <dataBit>CS8</dataBit>
        <stopBit>1</stopBit>
        <parity>none</parity>
        <flowControl>none</flowControl>
        <controlProtocol>PELCO_D</controlProtocol>
        <decoderType>0</decoderType>
        <controlAddress>1</controlAddress>
    </Serial>
</body>
