### ISSUE TITLE
argus pro support

### ISSUE THREAD

**Issue by nfgb** [jdillenkofer/camera_proxy#9]
Hi, does it support argus pro? I believe the only difference is the starlight sensor, so the communication should be identical. 
I've tried with my argus pro but it didn't work. I got no errors except for 404 when trying to accessing the web page.
Regarding the settings the deviceSid is the UID (if not how can I get it)?
This is what I get when running:

$python3 src/main.py --port 8002 --debug
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
INFO:werkzeug: * Running on http://0.0.0.0:8002/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN:

thanks

**Comment by jdillenkofer** [comment]
Hi,
what url did you try?
It should be 
http://localhost:8002/api/v1/cameras/[your_camera_name]/stream
for a mjpeg stream and
http://localhost:8002/api/v1/cameras/[your_camera_name]
for a image snapshot.

Regarding your second question: 
Yes, the deviceSid is the uid of the camera.

**Comment by nfgb** [comment]
I've tried the base url http://localhost:8002, I though it could be some index page with the links. I've even looked at the code although never programmed python ... but now I see it was there on the "@app.route(..."
It is working!
Thank you!

**Comment by Rockydell** [comment]
Hi Thank you so much for all the hard work you have put in . I have Argus 2 and tried your code.
Its working however the stream is lagging a bit and not very smooth. Also it after some time the video will go dark and comes back good. Probably it stops the stream for few seconds and starts back again. Is the any solution to this problem.
Thanks
